# Generated by Django 4.0.5 on 2022-06-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alias',
            field=models.CharField(help_text='Enter product alias', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='number',
            field=models.IntegerField(help_text='Enter product score', unique=True),
        ),
    ]
