# Generated by Django 4.0.5 on 2022-06-17 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedproduct',
            name='picture_path',
        ),
        migrations.CreateModel(
            name='TrainedProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_path', models.CharField(help_text='File path in FS', max_length=200)),
                ('trained_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainedproduct')),
            ],
        ),
    ]
