# Generated by Django 4.0.5 on 2022-06-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_trainedproduct_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedproduct',
            name='time_date',
            field=models.CharField(help_text='Date and time of creation', max_length=200, verbose_name='Created'),
        ),
    ]
