# Generated by Django 4.0.5 on 2022-06-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_trainedproduct_time_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainedproduct',
            old_name='time_date',
            new_name='date_time',
        ),
    ]
